### ISSUE TITLE
Small Bug / Possible Improvement

### ISSUE THREAD

**Issue by mlo0352** [Jesper-Hustad/personal-webpage#1]
There's a bug - this caps out after a certain number of bounces.
https://github.com/Jesper-Hustad/personal-webpage/blob/d5d1054eea22e1fd3da077b046a44182407a93dc/source/_posts/ae-dvd-bounce-expression.md?plain=1#L89

The following will fix it:
bounces * hueShift % 360

It works the same way, but doesn't get AE caught up with the "count * degrees" that it uses with hue shifts.

**Comment by Jesper-Hustad** [comment]
wow, never thought of people being able to send issues and bug reports trough Github. Just uploaded the site on here for hosting purposes. You are definitely right that is a bug and your solution works. Thanks for the tip!

Currently working on a complete revamp of the site with built in comments so it will be easier to give feedback.

**Comment by Jesper-Hustad** [comment]
New version of site now deployed with your fix included
![image](https://user-images.githubusercontent.com/17168694/170502395-bacdb797-9385-4ab9-8876-5c2f355e7b03.png)
